name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin
      - name: Build LimboFilter
        run: ./gradlew build

      - name: Upload LimboFilter
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "LimboFilter"
          automatic_release_tag: "lf"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/limbofilter*.jar"
          prerelease: true
