name: Java CI with Gradle

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 16 ]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.1
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Cache Gradle
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Build LimboFilter
        run: ./gradlew build
      - name: Upload LimboFilter
        uses: actions/upload-artifact@v2.2.4
        with:
          name: LimboFilter Built On ${{ matrix.java }} JDK
          path: "build/libs/limbofilter*.jar"
